org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.code.style=official

GROUP=com.jsoizo
VERSION_NAME=0.1.0-SNAPSHOT

POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/jsoizo/ktor-server-lambda/
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/license/mit
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/jsoizo/ktor-server-lambda/
POM_SCM_CONNECTION=scm:git:https://github.com/jsoizo/ktor-server-lambda.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/jsoizo/ktor-server-lambda.git
POM_DEVELOPER_ID=jsoizo
POM_DEVELOPER_NAME=jsoizo
POM_DEVELOPER_URL=https://github.com/jsoizo/
